version: "2"

services:
  app:
    container_name: "app"
    image: kaaass/wildfly-mysql:java-11-wildfly-23.0.0.Final-mysql-8.0
    environment:
      - WILDFLY_DEBUG=${WILDFLY_DEBUG}
      - WILDFLY_USER=${WILDFLY_ADMIN_USER}
      - WILDFLY_PASS=${WILDFLY_ADMIN_PASS}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_URI=db:3306
    depends_on:
      - db
    volumes:
      - ${DEPLOYMENT_PATH}:/opt/jboss/wildfly/standalone/deployments/:rw
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
      - "8787:8787" # java debug

  db:
    container_name: "db"
    image: "mysql:${MYSQL_VERSION}"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./workdir/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "13306:3306"

networks:
  default:
    driver: bridge
